### ISSUE TITLE
Not able to find link for the feed on the blog

### ISSUE THREAD

**Issue by rnestler** [dbrgn/blog#2]
I wasn't able to find the link for the feed https://blog.dbrgn.ch/feed.atom on the blog itself, but had to look into the pelicanconf.py...

**Comment by dbrgn** [comment]
<link href="https://blog.dbrgn.ch/feed.atom" type="application/atom+xml" rel="alternate" title="blog.dbrgn.ch Full Atom Feed" />

How is that not enough? :grin:

**Comment by rnestler** [comment]
Since I ultimately found it, we can close this issue :wink:

**Comment by dbrgn** [comment]
:heart:
